execute if block ~ ~ ~ minecraft:quartz_pillar[axis=x] positioned ~1 ~ ~ if block ~ ~ ~ minecraft:lime_glazed_terracotta[facing=east] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=x] positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:lime_glazed_terracotta[facing=east] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=z] positioned ~ ~ ~1 if block ~ ~ ~ minecraft:lime_glazed_terracotta[facing=south] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=z] positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:lime_glazed_terracotta[facing=south] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=y] positioned ~ ~1 ~ if block ~ ~ ~ minecraft:lime_glazed_terracotta[facing=north] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=y] positioned ~ ~-1 ~ if block ~ ~ ~ minecraft:lime_glazed_terracotta[facing=north] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff

execute if block ~ ~ ~ minecraft:quartz_pillar[axis=x] positioned ~1 ~ ~ if block ~ ~ ~ lime_glazed_terracotta[facing=west] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=x] positioned ~-1 ~ ~ if block ~ ~ ~ lime_glazed_terracotta[facing=west] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=z] positioned ~ ~ ~1 if block ~ ~ ~ lime_glazed_terracotta[facing=west] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=z] positioned ~ ~ ~-1 if block ~ ~ ~ lime_glazed_terracotta[facing=west] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=y] positioned ~ ~1 ~ if block ~ ~ ~ lime_glazed_terracotta[facing=west] run return run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff
execute if block ~ ~ ~ minecraft:quartz_pillar[axis=y] positioned ~ ~-1 ~ if block ~ ~ ~ lime_glazed_terracotta[facing=west] run function datapipes_lib:fluid_transfer/quartz_pipe_checks/connectedquartzpipesoff