setblock ~ ~ ~ minecraft:granite_slab[type=double]
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:red_glazed_terracotta[facing=east] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:red_glazed_terracotta[facing=east] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~ ~1 ~ if block ~ ~ ~ minecraft:red_glazed_terracotta[facing=north] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~ ~-1 ~ if block ~ ~ ~ minecraft:red_glazed_terracotta[facing=north] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:red_glazed_terracotta[facing=south] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:red_glazed_terracotta[facing=south] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~1 ~ ~ if block ~ ~ ~ red_glazed_terracotta[facing=west] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~-1 ~ ~ if block ~ ~ ~ red_glazed_terracotta[facing=west] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~ ~1 ~ if block ~ ~ ~ red_glazed_terracotta[facing=west] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~ ~-1 ~ if block ~ ~ ~ red_glazed_terracotta[facing=west] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~ ~ ~1 if block ~ ~ ~ red_glazed_terracotta[facing=west] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off
execute positioned ~ ~ ~-1 if block ~ ~ ~ red_glazed_terracotta[facing=west] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_off