setblock ~ ~ ~ red_glazed_terracotta[facing=west]
execute positioned ~1 ~ ~ if block ~ ~ ~ chain[axis=x] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~-1 ~ ~ if block ~ ~ ~ chain[axis=x] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~ ~1 ~ if block ~ ~ ~ chain[axis=y] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~ ~-1 ~ if block ~ ~ ~ chain[axis=y] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~ ~ ~1 if block ~ ~ ~ chain[axis=z] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~ ~ ~-1 if block ~ ~ ~ chain[axis=z] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:granite_slab[type=double] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:granite_slab[type=double] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~ ~1 ~ if block ~ ~ ~ minecraft:granite_slab[type=double] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~ ~-1 ~ if block ~ ~ ~ minecraft:granite_slab[type=double] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:granite_slab[type=double] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:granite_slab[type=double] run function datapipes_lib:power_transfer/wire_connection_check/connected_wires_on
